"""Constants and configuration thresholds for Truth Mirror."""

# Verdict Thresholds
VERDICT_MIN_QUALITY = 0.45
VERDICT_UNCLEAR_BASE_CONFIDENCE = 0.25
VERDICT_UNCLEAR_NO_SUPPORT_CONFIDENCE = 0.35
VERDICT_UNCLEAR_FALLBACK_CONFIDENCE = 0.3
VERDICT_UNSUPPORTED_CONFIDENCE = 0.45
VERDICT_PARTIALLY_SUPPORTED_CONFIDENCE = 0.55

VERDICT_SUPPORTED_CAP = 0.9
VERDICT_CONTRADICTED_CAP = 0.9
VERDICT_DISPUTED_CAP = 0.7

VERDICT_EMPTY_CONFIDENCE = 0.2
VERDICT_EMPTY_CONFIDENCE_INTERVAL = (0.0, 0.4)

VERDICT_MAX_INTERVAL_WIDTH = 0.6

# Abstention / Uncertainty Thresholds
ABSTENTION_MIN_INDEPENDENCE = 0.3
ABSTENTION_MIN_QUALITY = 0.3
ABSTENTION_MAX_INSUFFICIENT_RATIO = 0.7

# Uncertainty Margin Weights
UNCERTAINTY_WEIGHT_INSUFFICIENT = 0.2
UNCERTAINTY_WEIGHT_NEUTRAL = 0.1
UNCERTAINTY_WEIGHT_CONFLICT = 0.3
UNCERTAINTY_WEIGHT_QUALITY = 0.2
UNCERTAINTY_WEIGHT_INDEPENDENCE = 0.1
